kind: pipeline
name: deploy
type: exec
steps:
  - name: buildandpush
    image: docker:latest
    environment:
      AZURE_CONTAINER_REGISTRY: secureuploadregistry.azurecr.io
      AZURE_CONTAINER_REGISTRY_USERNAME: secureuploadregistry
      AZURE_CONTAINER_REGISTRY_PASSWORD:
        from_secret: AZURE_CONTAINER_REGISTRY_PASSWORD
    commands:
    - docker build -t $AZURE_CONTAINER_REGISTRY/secureupload:latest .
    - docker login --username $AZURE_CONTAINER_REGISTRY_USERNAME --password $AZURE_CONTAINER_REGISTRY_PASSWORD $AZURE_CONTAINER_REGISTRY
    - docker push $AZURE_CONTAINER_REGISTRY/secureupload:latest
trigger:
  event:
    - push
  branch:
    - master