# TEST ONLY FOR DEVELOP BRANCH
kind: pipeline
name: test
type: docker
trigger:
  event:
    - push
  branch:
    - develop
steps:
  - name: test
    image: mvn:latest
    commands:
      - mvn test
---
# TEST, BUILD AND PUSH TO PRODUCTION FOR MASTER BRANCH
kind: pipeline
name: deploy
type: docker
trigger:
  event:
    - push
  branch:
    - master
steps:
  - name: test
    image: mvn:latest
    commands:
      - mvn test
  - name: buildandpush
    image: plugins/docker
    settings:
      registry: secureuploadregistry.azurecr.io
      username: secureuploadregistry
      password:
        from_secret: AZURE_CONTAINER_REGISTRY_PASSWORD
      repo: secureuploadregistry.azurecr.io/secureupload
      tags:
        - latest
