---
kind: pipeline
name: test

services:
  - name: database
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: secret

steps:
- name: wait for database
  image: mariadb
  commands: 
    - while ! mysqladmin -u root -h database ping --silent; do sleep 1; done
- name: test
  image: maven:3-jdk-11
  environment:
    MYSQL_URL: jdbc:mysql://database:3306/db_name
    MYSQL_USER: db_user
    MYSQL_PASSWORD: secret
  commands:
    - mvn test -B

trigger:
  event:
    - push

---
kind: pipeline
name: deploy

steps:
  - name: create settings.xml
    image: maven:3-jdk-11
    environment:
      AZURE_CLIENT_ID:
        from_secret: AZURE_CLIENT_ID
      AZURE_TENANT_ID:
        from_secret: AZURE_TENANT_ID
      AZURE_KEY:
        from_secret: AZURE_KEY
    commands: 
      - sed -i "s/CLIENT_ID/${AZURE_CLIENT_ID}/g" settings.ci.xml
      - sed -i "s/TENANT_ID/${AZURE_TENANT_ID}/g" settings.ci.xml
      - sed -i "s/AZURE_KEY/${AZURE_KEY}/g" settings.ci.xml
  - name: deploy
    image: maven:3-jdk-11
    commands:
    - mvn --settings ./settings.ci.xml azure-app:deploy

trigger:
  event:
    - push
  branch:
    - master