kind: pipeline
name: test

services:
  - name: database
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: secret

steps:
- name: test
  image: maven:3-jdk-11
  environment:
    MYSQL_URL: jdbc:mysql://127.0.0.1:3306/db_name
    MYSQL_USER: db_user
    MYSQL_PASSWORD: secret
  commands:
  - ./mvnw test

trigger:
  event:
    - push