kind: pipeline
name: deploy
type: docker
steps:
  - name: buildandpush
    image: plugins/docker
    settings:
      registry: secureuploadregistry.azurecr.io
      username: secureuploadregistry
      password:
        from_secret: AZURE_CONTAINER_REGISTRY_PASSWORD
      repo: secureuploadregistry.azurecr.io/secureupload
      tags:
        - latest
trigger:
  event:
    - push
  branch:
    - master