# TEST ONLY FOR DEVELOP BRANCH
kind: pipeline
name: test
type: docker
trigger:
  event:
    - push
  branch:
    - develop
    - master
steps:
  - name: test
    image: maven:latest
    environment:
      MYSQL_URL: jdbc:mysql://database:3306/secureupload
      MYSQL_USER: secureupload
      MYSQL_PASSWORD: DatabasePassword12345
      SMTP_HOST: smtp
      SMTP_PORT: 1025
      ADMIN_EMAIL: renaud@secureupload.com
      ADMIN_PASSWORD: Password12345
      JWT_SECRET: SecretForDevOnly
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=https;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=https://storage:10000/devstoreaccount1;
      AZURE_STORAGE_CONTAINER_NAME: my-container
      VIRUS_TOTAL_API_KEY:
        from_secret: VIRUS_TOTAL_API_KEY
    commands:
      - chmod 500 ./scripts/*.sh
      - ./scripts/start.sh database:3306 storage:10000 smtp:1025 smtp:8025
      - mvn test
services:
  - name: database
    image: mariadb:latest
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: secureupload
        MYSQL_USER: secureupload
        MYSQL_PASSWORD: DatabasePassword12345
    ports:
      - 3306
  - name: storage
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000
  - name: smtp
    image: mailhog/mailhog:latest
    ports:
      - 1025
      - 8025
---
# BUILD AND PUSH TO PRODUCTION FOR MASTER BRANCH
kind: pipeline
name: deploy
type: docker
trigger:
  event:
    - push
  branch:
    - master
steps:
  - name: buildandpush
    image: plugins/docker
    settings:
      registry: secureuploadregistry.azurecr.io
      username: secureuploadregistry
      password:
        from_secret: AZURE_CONTAINER_REGISTRY_PASSWORD
      repo: secureuploadregistry.azurecr.io/secureupload
      tags:
        - latest
depends_on:
  - test