kind: pipeline
name: deploy
type: docker
steps:
  - name: buildandpush
    image: plugins/docker
    environment:
      AZURE_CONTAINER_REGISTRY: secureuploadregistry.azurecr.io
      AZURE_CONTAINER_REGISTRY_USERNAME: secureuploadregistry
      AZURE_CONTAINER_REGISTRY_PASSWORD:
        from_secret: AZURE_CONTAINER_REGISTRY_PASSWORD
    settings:
      username: $AZURE_CONTAINER_REGISTRY_USERNAME
      password: $AZURE_CONTAINER_REGISTRY_PASSWORD
      repo: secureupload
      registry: $AZURE_CONTAINER_REGISTRY
      tags:
        - latest
trigger:
  event:
    - push
  branch:
    - master