kind: pipeline
name: deploy
type: docker
steps:
  - name: buildandpush
    image: plugins/docker
    environment:
      AZURE_CONTAINER_REGISTRY_PASSWORD:
        from_secret: AZURE_CONTAINER_REGISTRY_PASSWORD
    settings:
      username: secureuploadregistry
      password:
        from_secret: docker_password
      repo: secureupload
      registry: secureuploadregistry.azurecr.io
      tags:
        - latest
trigger:
  event:
    - push
  branch:
    - master