kind: pipeline
name: deploy
type: exec
steps:
  - name: buildandpush
    image: microsoft/azure-cli:latest
    environment:
      AZURE_CONTAINER_REGISTRY: secureuploadregistry.azurecr.io
      AZURE_CONTAINER_REGISTRY_USERNAME: secureuploadregistry
      AZURE_CONTAINER_REGISTRY_PASSWORD:
        from_secret: AZURE_CONTAINER_REGISTRY_PASSWORD
    commands:
    - az acr login --username $AZURE_CONTAINER_REGISTRY_USERNAME --password $AZURE_CONTAINER_REGISTRY_PASSWORD --name $AZURE_CONTAINER_REGISTRY
    - az acr build --registry $AZURE_CONTAINER_REGISTRY/secureupload:latest .
    - az logout
trigger:
  event:
    - push
  branch:
    - master