version: '3'
services:
    api:
        image: secureupload:latest
        environment:
            MYSQL_URL: jdbc:mysql://glkojooepk-mysql-server.mysql.database.azure.com:3306/secureupload?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            MYSQL_USER: secureupload@glkojooepk-mysql-server
            MYSQL_PASSWORD: Password12345
            SMTP_HOST: tmp_smtp_host
            SMTP_PORT: 465
            SMTP_USER: tmp_smtp_user
            SMTP_PASSWORD: tmp_smtp_password
            ADMIN_EMAIL: renaud@secureupload.com
            ADMIN_PASSWORD: Password123
            JWT_SECRET: Secret
        ports:
            - '8080:8080'
        restart: on-failure