version: '3'
services:
    app:
        image: maven:3-jdk-11
        environment:
            MYSQL_URL: jdbc:mysql://mariadb:3306/db_name
            MYSQL_USER: db_user
            MYSQL_PASSWORD: secret
            SMTP_HOST: tmp_smtp_host
            SMTP_PORT: 465
            SMTP_USER: tmp_smtp_user
            SMTP_PASSWORD: tmp_smtp_password
        networks:
            - backend
        ports:
            - '8080:8080'
        restart: on-failure
        volumes:
            - .:/app
        working_dir: /app
        command: "mvn spring-boot:run"
        depends_on:
            - mariadb
    mariadb:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db_name
            MYSQL_USER: db_user
            MYSQL_PASSWORD: secret
        networks:
            - backend
        ports:
            - '3306:3306'
        restart: on-failure
        volumes:
            - databaseVolume:/var/lib/mysql
volumes:
    databaseVolume: {}
networks:
    backend:
        driver: bridge