version: '2.4'
services:

    api:
        image: maven:latest
        environment:
            MYSQL_URL: jdbc:mysql://database:3306/secureupload
            MYSQL_USER: secureupload
            MYSQL_PASSWORD: DatabasePassword12345
            SMTP_HOST: smtp
            SMTP_PORT: 1025
            SMTP_USER: secureupload@secureupload.com
            SMTP_PASSWORD: SmtpPassword12345
            ADMIN_EMAIL: renaud@secureupload.com
            ADMIN_PASSWORD: Password12345
            JWT_SECRET: SecretForDevOnly
            AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://storage:10000/devstoreaccount1;
            AZURE_STORAGE_CONTAINER_NAME: my-container
            VIRUS_TOTAL_API_KEY:
        ports:
            - '8080:8080'
        volumes:
        - ../:/secureupload
        working_dir: /secureupload
        command: [ "bash", "-c", "./scripts/start.sh database:3306 storage:10000 smtp:1025 smtp:8025 && mvn spring-boot:run" ]
        depends_on:
          - database
          - smtp
          - storage
        restart: always
    database:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: secureupload
            MYSQL_USER: secureupload
            MYSQL_PASSWORD: DatabasePassword12345
        ports:
            - "3306"
    storage:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
         - "10000"
    smtp:
        image: mailhog/mailhog:latest
        ports:
            - "1025:1025"
            - "8025:8025"
